#include: package:lint/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    camel_case_types: false               # Classes and typedefs should capitalize
    leading_newlines_in_multiline_strings: false
    use_build_context_synchronously: false
    avoid_dynamic_calls: false             # use .method() on dynamic object



analyzer:
  errors:
    prefer_single_quotes: error
    mixin_inherits_from_not_object: warning
    invalid_assignment: error           # ignore assign dynamic to type (int x = js['x'])
    argument_type_not_assignable: error # for argument of methods, (dynamic or nullable) to Types


  exclude:
    - \#Dep/**



#------------------------------------------------------------
# ignore single line:
#  above file >  // ignore_for_file: invalid_assignment
#  above line >  // ignore: non_constant_identifier_names

# ignore all files:
#  in this file >     non_constant_identifier_names: false

#------- Roles -----------------------------------------------------
#     avoid_print
#     use_build_context_synchronously: false
#     prefer_const_constructors: false      # const in new instance
#     prefer_const_constructors_in_immutables: false
#     prefer_const_declarations: false      # const in class constructor
#     prefer_const_literals_to_create_immutables: false
#     avoid_classes_with_only_static_members: true
#     file_names: false
#     always_declare_return_types
#     annotate_overrides
#     avoid_empty_else
#     avoid_init_to_null
#     avoid_return_types_on_setters
#     await_only_futures
#     camel_case_types
#     cancel_subscriptions
#     close_sinks
#     comment_references
#     control_flow_in_finally
#     empty_catches
#     empty_constructor_bodies
#     empty_statements
#     hash_and_equals
#     implementation_imports
#     invariant_booleans
#     iterable_contains_unrelated_type

#     constant_identifier_names
#     library_names
#     package_names
#     package_prefixed_library_names
#     non_constant_identifier_names

#     library_prefixes
#     list_remove_unrelated_type
#     literal_only_boolean_expressions
#     one_member_abstracts
#     overridden_fields
#     package_api_docs
#     prefer_final_fields
#     prefer_final_locals
#     prefer_is_not_empty
#     slash_for_doc_comments
#     sort_unnamed_constructors_first
#     test_types_in_equals
#     throw_in_finally
#     type_annotate_public_apis
#     type_init_formals
#     unawaited_futures
#     unnecessary_brace_in_string_interps
#     unnecessary_getters_setters
#     unrelated_type_equality_checks
#     valid_regexps
#     always_require_non_null_named_parameters
#     avoid_null_checks_in_equality_operators
#     avoid_relative_lib_imports
#     avoid_shadowing_type_parameters
#     avoid_single_cascade_in_expression_statements
#     avoid_types_as_parameter_names
#     camel_case_extensions
#     curly_braces_in_flow_control_structures
#     no_duplicate_case_values
#     null_closures
#     omit_local_variable_types
#     prefer_adjacent_string_concatenation
#     prefer_collection_literals
#     prefer_conditional_assignment
#     prefer_contains
#     prefer_equal_for_default_values
#     prefer_for_elements_to_map_fromIterable
#     prefer_generic_function_type_aliases
#     prefer_if_null_operators
#     prefer_inlined_adds
#     prefer_is_empty
#     prefer_iterable_whereType
#     prefer_single_quotes
#     prefer_spread_collections
#     recursive_getters
#     sort_child_properties_last
#     unnecessary_const
#     unnecessary_new
#     unnecessary_null_in_if_null_operators
#     unnecessary_this
#     unsafe_html
#     use_full_hex_values_for_flutter_colors
#     use_function_type_syntax_for_parameters
#     use_rethrow_when_possible
#     leading_newlines_in_multiline_strings: false
#    avoid_dynamic_calls
#------------------------------------------------------------
# Lints List:
#   https://dart.dev/tools/linter-rules
#   https://dart.dev/tools/linter-rules/all
#   https://gist.github.com/rydmike/fa5c991118ab712f35d2285e7b8a82cb
#

# Help find name:
# https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=invalid_assignment#invalid_assignment
# https://dart.dev/guides/language/analysis-options
