# Flutter: 3.19.0      old: 3.14.3
# Dart: 3.3.0        old: 3.1.0
# Java: 17

name: app     		  # vosate_zehn
description: meditation app
homepage: https://vosatezehn.ir
#repository: https://github.com/...

publish_to: 'none'

version: 5.4.0+31


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'


dependencies:
  flutter:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter

  #device_preview: ^1.1.0
  #cupertino_icons: ^1.0.6
  community_material_icon: ^5.9.55      # https://materialdesignicons.com/  https://www.fluttericon.com/
  device_info_plus: ^10.1.0
  platform_device_id: ^1.0.1
  permission_handler: ^11.3.1            # NoWeb
  flutter_spinkit: ^5.2.1
  video_player: ^2.8.6
  chewie: ^1.8.1
  audioplayers: ^6.0.0
  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.2
  url_launcher: ^6.2.6
  material_dialogs: ^1.1.4
  awesome_notifications: ^0.9.3+1                 # do not upgrade, occur error, 0.6.21, 0.8.2
  stop_watch_timer: ^3.1.1
  iris_notifier: ^0.0.8
  numberpicker: ^2.1.2
  pull_to_refresh: ^2.0.0
  image_picker: ^1.1.0
  file_picker: ^8.0.1
  toggle_switch: ^2.3.0
  firebase_messaging: ^14.8.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  lottie: ^3.1.0
  move_to_background: ^1.0.2
  workmanager: ^0.5.2
  simple_animations: ^5.0.2
  animate_do: ^3.3.4                   # https://animate.style/
  badges: ^3.1.2
  photo_view: ^0.15.0                   # image view gallery
  google_sign_in: ^6.2.1
  google_sign_in_web: any
  #sign_in_with_apple: ^4.0.0
  pin_code_fields: ^8.0.1
  shaped_bottom_bar: ^1.1.0
  share_extend: ^2.0.0
  flutter_html: ^2.2.1
  webviewx: ^0.2.2
  flutter_custom_clippers: ^2.1.0
  glowstone: ^0.0.2
  appinio_swiper: ^2.1.1
  wakelock: ^0.6.2
  carousel_slider: ^4.2.1
  flutter_flip_card: ^0.0.5
  flutter_poolakey: ^2.2.0
  android_intent_plus: ^5.0.2


  iris_tools:
    git: https://github.com/ali-1989/IrisTools.git
#    path: ../../#FlutterPackages/IrisTools
  iris_db:
    git: https://github.com/ali-1989/IrisDB.git
  iris_download_manager:
    git: https://github.com/ali-1989/IrisDownloadManager.git
  iris_websocket:
    git: https://github.com/ali-1989/IrisWebSocket.git
  iris_pic_editor:
    git: https://github.com/ali-1989/IrisPicEditor.git
  iris_runtime_cache:
    git: https://github.com/ali-1989/irisRuntimeCache.git
  iris_route:
    git: https://github.com/ali-1989/iris_route.git


dependency_overrides:
  win32: ^5.3.0    # 4.1.4,5.1.1  device_info_plus, wakelock_windows
  flutter_svg: 1.1.6 # xml 1.1.6
  http: ^1.2.1   # webviewx
  intl: ^0.19.0
  lottie: ^3.1.0
  flutter_layout_grid: ^2.0.6 # do not remove this, this is occurred error on build time


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true

  # Image.asset('assets/images/x.jpg')
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/
    - assets/audio/
    - assets/raw/


  #style: italic  weight: 700
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Nazanin # base-sub
      fonts:
        - asset: assets/fonts/nazanin-base-sub.ttf
    - family: Sans # sub
      fonts:
        - asset: assets/fonts/sans-sub.ttf
    - family: IranSans # any
      fonts:
        - asset: assets/fonts/iran-sans.ttf
    - family: Icomoon # any
      fonts:
        - asset: assets/fonts/icomoon.ttf


flutter_icons:
  image_path: "#Dep/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 96


import_sorter:
  emojis: false
  comments: false


  # ** packages that for iOS needs additional code:
  # https://pub.dev/packages/just_audio#ios
  # https://pub.dev/packages/url_launcher#ios
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-ios
  #https://pub.dev/packages/flutter_local_notifications#general-setup
  # https://pub.dev/packages/video_player#ios
  # https://pub.dev/packages/image_picker#ios
  # https://pub.dev/packages/flutter_local_auth_invisible#ios-integration
  # https://pub.dev/packages/network_info_plus

  # ** packages that for Android needs additional code:
  # https://pub.dev/packages/url_launcher#android
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-android
  # https://pub.dev/packages/pinput#android
  # https://pub.dev/packages/network_info_plus


## dart run import_sorter:main
## dart run flutter_launcher_icons

# import '[^pd/]

# caret sign:
# ^0.1.2 is the same as '>=0.1.2 <0.2.0'
# ^1.2.3 would be the same as '>=1.2.3 <2.0.0'
# if not use caret sign , force download/use that version

# --web-port=5000 --dart-define=flavor=bazar_local_resetHttp