# Flutter: 3.3.4      old: 3.3.2
# Dart: 2.18.2        old: 2.17.1
# Java: 17    gradle.properties (org.gradle.java.home)

name: app     		  # vosate_zehn
description: meditation app
homepage: https://iris.ir
#repository: https://github.com/...

publish_to: 'none'

version: 5.2.12+25


environment:
  sdk: ">=2.18.0"             # null Safety : 2.12.0
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1 # image: 3.0.2  xml: ^5.0.0

  flutter_localizations:
    sdk: flutter

  #device_preview: ^1.1.0
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.10
  community_material_icon: ^5.9.55      # https://materialdesignicons.com/
  device_info_plus: ^8.2.0
  platform_device_id: ^1.0.1
  permission_handler: ^10.2.0            # NoWeb
  flutter_spinkit: ^5.1.0
  video_player: ^2.6.1
  chewie: ^1.4.0
  http: ^0.13.5
  dio: ^5.1.1
  material_dialogs: ^1.1.4
  awesome_notifications: 0.6.21                 # can not upgrade to new, occur error, 0.6.21
  popover: ^0.2.8+2
  stop_watch_timer: ^2.0.0
  iris_notifier: ^0.0.3
  numberpicker: ^2.1.2
  just_audio: ^0.9.32
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.7+4
  toggle_switch: ^2.1.0
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  lottie: ^2.3.2
  file_picker: ^5.2.11
  connectivity_plus: ^3.0.4
  move_to_background: ^1.0.2
  workmanager: ^0.5.1
  simple_animations: ^5.0.0+3
  animate_do: ^3.0.2                   # https://animate.style/
  badges: ^3.1.1
  photo_view: ^0.14.0                   # image view gallery
  google_sign_in: ^6.1.0
  #sign_in_with_apple: ^4.0.0
  pin_code_fields: ^7.4.0
  shaped_bottom_bar: ^1.1.0
  share_extend: ^2.0.0
  flutter_html: ^2.2.1
  webviewx: ^0.2.2
  flutter_custom_clippers: ^2.1.0
  glowstone: ^0.0.2
  appinio_swiper: ^2.0.0
  wakelock: ^0.6.2
  carousel_slider: ^4.2.1
  flutter_flip_card: ^0.0.4


  iris_tools:
    #path: ../IrisTools
    git: https://github.com/ali-1989/IrisTools.git
  iris_db:
    git: https://github.com/ali-1989/IrisDB.git
  iris_download_manager:
    git: https://github.com/ali-1989/IrisDownloadManager.git
  iris_websocket:
    git: https://github.com/ali-1989/IrisWebSocket.git
  iris_pic_editor:
    git: https://github.com/ali-1989/IrisPicEditor.git
  iris_runtime_cache:
    git: https://github.com/ali-1989/irisRuntimeCache.git
  iris_route:
    git: https://github.com/ali-1989/iris_route.git


  # ** packages that for iOS needs additional code:
  # https://pub.dev/packages/just_audio#ios
  # https://pub.dev/packages/url_launcher#ios
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-ios
  # https://pub.dev/packages/video_player#ios
  # https://pub.dev/packages/image_picker#ios

  # ** packages that for Android needs additional code:
  # https://pub.dev/packages/url_launcher#android
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-android
  # https://pub.dev/packages/pinput#android

dependency_overrides:
  path: 1.8.3     # flutter_test
  ffi: 2.0.1      # device_info_plus
  intl: 0.18.1    # awesome_notifications
  xml: 6.2.2
  win32: 4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  # Image.asset('assets/images/x.jpg')
  assets:
    - assets/images/
    - assets/locales/
    - assets/audio/
    - assets/raw/

  #style: normal  # normal, italic
  #style: italic  weight: 700
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Nazanin # base-sub
      fonts:
        - asset: assets/fonts/nazanin-base-sub.ttf
    - family: Sans # sub
      fonts:
        - asset: assets/fonts/sans-sub.ttf
    - family: IranSans # any
      fonts:
        - asset: assets/fonts/iran-sans.ttf
    - family: Icomoon # any
      fonts:
        - asset: assets/fonts/icomoon.ttf


flutter_icons:
  image_path: "dep/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 96


import_sorter:
  emojis: false
  comments: false


## flutter pub run import_sorter:main
## flutter pub run flutter_launcher_icons:main

# import '[^pd/]

# caret sign:
# ^0.1.2 is the same as '>=0.1.2 <0.2.0'
# ^1.2.3 would be the same as '>=1.2.3 <2.0.0'
# if not use caret sign , force download/use that version.
