// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:731359726004:web:7b371dd04042f69cb20ae1',
    apiKey: 'AIzaSyC2gsyD1HYpP6LwXws6hZc_PTFoK68rl8c',
    projectId: 'vosate-zehn-7d8fe',
    messagingSenderId: '731359726004',
    measurementId: 'G-8ZKZGGLXRW',

    authDomain: 'vosate-zehn-7d8fe.firebaseapp.com',
    storageBucket: 'vosate-zehn-7d8fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:731359726004:android:fbbd8cd236c4fc31b20ae1',
    apiKey: 'AIzaSyBVuGcqQFjUl1t5mIUJ04rfr9EKkDRqYxM',
    projectId: 'vosate-zehn-7d8fe',
    messagingSenderId: '731359726004',
    measurementId: 'G-8ZKZGGLXRW',

    storageBucket: 'vosate-zehn-7d8fe.appspot.com',
    //androidClientId: '579668054514-c17kvvimm81is6pfpfrl31n8gmnn7kii.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJ8hT0YxEDeJeSaM3Obw3My5eOStrcUI',
    appId: '1:579668054514:ios:faa5a4589225dffbd79b6b',
    messagingSenderId: '579668054514',
    projectId: 'green-oasis-2023',
    storageBucket: 'green-oasis-2023.appspot.com',
    androidClientId: '579668054514-c17kvvimm81is6pfpfrl31n8gmnn7kii.apps.googleusercontent.com',
    iosClientId: '579668054514-dg2h9sv7qa0nm05bnkqsr8ivgj605v97.apps.googleusercontent.com',
    iosBundleId: 'ir.iris.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJ8hT0YxEDeJeSaM3Obw3My5eOStrcUI',
    appId: '1:579668054514:ios:5dbe35562222618dd79b6b',
    messagingSenderId: '579668054514',
    projectId: 'green-oasis-2023',
    storageBucket: 'green-oasis-2023.appspot.com',
    androidClientId: '579668054514-c17kvvimm81is6pfpfrl31n8gmnn7kii.apps.googleusercontent.com',
    iosClientId: '579668054514-n39tpm6sblnmk38gcfp6577f9fi4ihdh.apps.googleusercontent.com',
    iosBundleId: 'ir.iris.green.RunnerTests',
  );

  static const String fcmKey = 'BLkHyiaxrQJA7eSDwjrCos0BcsGVPjxM8JGXJ1CFBAeFa2wNGoJDGkOJu6CqsPhjwhf2_EII8SoJmos0TqMOitE';
}
